#version: '3.8'  # Specify the Docker Compose version

services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "Y"  # Correct syntax for accepting the EULA
      MSSQL_SA_PASSWORD: "Password@1"  # Correct syntax for setting the SA password
    ports:
      - "1433:1433"  # Correct syntax for port mapping

  app:
    image: appregistryskinet.azurecr.io/skinet-api
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql;Database=skinet;User=sa;Password=Password@1;Encrypt=False;  # Updated connection string
    ports:
      - "5000:5000"  # Expose .NET Core app on port 5000
    depends_on:
      - sql  # Ensure SQL starts before the app

  app2:
    image: suyen05/docker-skinet
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql;Database=skinet;User=sa;Password=Password@1;Encrypt=False;  # Updated connection string
    ports:
      - "5000:8080"  # Expose .NET Core app on port 5000
    depends_on:
      - sql  # Ensure SQL starts before the app